FROM python:3.9-slim-buster

# Set working directory
WORKDIR .

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy rest of the app
COPY source /source

# Expose port for the API
EXPOSE 8000

# Run the command to start the API
CMD ["uvicorn", "mindgard_api.main:app", "--host", "0.0.0.0", "--port", "8000"]