name: Deploy

on:
  push:
    branches:
    - master

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Login to Azure
      run: |
        az login \
          --service-principal \
          -u $client_id \
          -p $client_secret \
          --tenant $tenant_id
    